server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/

spring:
  application:
    name: article
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://188.131.233.41:3306/coode

mybatis:
  mapper-locations: classpath:mapper/*.xml
